# Generated by Django 2.2.16 on 2020-09-29 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('disponible', models.BooleanField(default=True)),
                ('promo', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Carte',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=150, verbose_name='sujet')),
                ('message', models.CharField(max_length=2000, verbose_name='message')),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localite', models.CharField(max_length=200)),
                ('sponsor', models.CharField(max_length=100)),
                ('avis', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
                ('relais', models.CharField(blank=True, max_length=200)),
                ('agence', models.CharField(blank=True, choices=[('MARCORY', (('MARCORY SANS FIL +225 58 73 77 63', 'MARCORY SANS FIL +225 58 73 77 63'),)), ('KOUMASSI', (('MARCORY ETS TONY REMBLAIS COLLEGE COLOMBE +225 07215421', 'MARCORY ETS TONY REMBLAIS COLLEGE COLOMBE +225 07215421'),))], max_length=100)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('retiree', models.BooleanField(default=False)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Carte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
            },
        ),
    ]
